version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo-payment
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper-service
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-service
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  bank-mock-service:
    build:
      context: ../BankApiMockService
      dockerfile: Dockerfile
    container_name: bank-mock-service
    restart: unless-stopped
    ports:
      - "8085:8085"

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_started
      kafka:
        condition: service_healthy
      bank-mock-service:
        condition: service_started
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DOCKER_SPRING_MONGODB_URI: ${DOCKER_SPRING_MONGODB_URI}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_KAFKA_BOOTSTRAP_SERVERS}
      EXTERNAL_SERVICE_URL: ${DOCKER_EXTERNAL_SERVICE_URL}
      TOPIC_NAME: ${TOPIC_NAME}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  mongodb_data: