server:
  port: 8084
spring:
  application:
    name: PaymentService
  data:
    mongodb:
      port: ${MONGODB_PORT}
      host: ${MONGODB_HOST}
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
api:
  user:
    uri: ${EXTERNAL_SERVICE_URL:}