apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: DOCKER_SPRING_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DOCKER_SPRING_MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: USER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_SERVICE_URL
            - name: DOCKER_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: TOPIC_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TOPIC_NAME
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 120
            periodSeconds: 15